'scope: docs':
  - docs/**/*

'scope: web':
  - public/**/*
  - src/**/*


'scope: api':
  - api/**/*

# 'platform: api':
#   - api-server/**/*
#   - api/**/*

'scope: tools/scripts':
  # - cypress/**/*
  # - tools/**/*
  - .github/**/*
  # - utils/**/*

# 'scope: i18n':
#   - any: ['curriculum/challenges/**/*', '!curriculum/challenges/english/**/*']
#   - docs/i18n/**/*
#   - client/i18n/**/*
#   - config/crowdin/**/*
#   - config/i18n/**/*